apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-challenge-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sport-enlace-sas/frontend-challenge-base'
    targetRevision: main
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
